language: java
sudo: required
dist: bionic
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
   - echo $JAVA_HOME
matrix:
  include:
    - os: linux
      jdk: openjdk11
    - os: osx
      jdk: openjdk11
    - os: windows
      jdk: openjdk11
install:
  - mvn clean install -DskipTests=true
script:
  - mvn clean test -DstorageEngine=InMemory
  - mvn clean test -DstorageEngine=MapDB
notifications:
  email:
    on_success: never
    on_failure: always
