version: '{build}'

image: Visual Studio 2019

environment:
  JAVA_HOME: 'C:\Program Files\Java\jdk11'
install:
  - cmd: echo "%JAVA_HOME%"
  - cmd: set PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: echo "%PATH%"
  - cmd: java -version
  - ps: choco install -i maven
  - cmd: mvn --version
build_script:
  - mvn clean install -DskipTests=true
test_script:
  - mvn clean test -DstorageEngine=InMemory
  - mvn clean test -DstorageEngine=MapDB
cache:
  - C:\Users\appveyor\.m2